<?php
session_start();
if (!isset($_SESSION['admin'])) {
    header("Location: login.php");
    exit;
}
require 'config.php';
require 'vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

// Fetch employees for dropdown
$employees = $conn->query("SELECT id, name FROM employees ORDER BY name")->fetchAll(PDO::FETCH_ASSOC);

$message = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $employee_id = $_POST['employee_id'] ?? '';
    $month       = $_POST['month'] ?? '';
    $year        = $_POST['year'] ?? '';
    $basic       = $_POST['basic'] ?? 0;
    $hra         = $_POST['hra'] ?? 0;
    $allowance   = $_POST['allowance'] ?? 0;
    $deductions  = $_POST['deductions'] ?? 0;

    if ($employee_id && $month && $year) {
        // Check employee exists
        $stmt = $conn->prepare("SELECT id, name FROM employees WHERE id = ?");
        $stmt->execute([$employee_id]);
        $employee = $stmt->fetch(PDO::FETCH_ASSOC);

        if ($employee) {
            // Create payslips folder if not exists
            $folder = 'payslips/';
            if (!is_dir($folder)) mkdir($folder, 0777, true);

            // File name
            $filename = $folder . "payslip_{$employee['name']}_{$month}_{$year}.pdf";

            // Calculate net pay
            $netPay = $basic + $hra + $allowance - $deductions;

            // HTML
            $html = "
            <h2 style='text-align:center;'>Payslip for {$month} {$year}</h2>
            <table border='1' cellspacing='0' cellpadding='10' style='width:60%; margin:auto; border-collapse: collapse;'>
                <tr><th>Employee Name</th><td>{$employee['name']}</td></tr>
                <tr><th>Basic Salary</th><td>₹".number_format($basic,2)."</td></tr>
                <tr><th>HRA</th><td>₹".number_format($hra,2)."</td></tr>
                <tr><th>Allowance</th><td>₹".number_format($allowance,2)."</td></tr>
                <tr><th>Deductions</th><td>₹".number_format($deductions,2)."</td></tr>
                <tr><th>Net Pay</th><td><strong>₹".number_format($netPay,2)."</strong></td></tr>
            </table>
            <p style='text-align:center; margin-top:20px;'>Generated by Office Employee Management System</p>";

            // Generate PDF
            $options = new Options();
            $options->set('isRemoteEnabled', true);
            $dompdf = new Dompdf($options);
            $dompdf->loadHtml($html);
            $dompdf->setPaper('A4', 'portrait');
            $dompdf->render();
            file_put_contents($filename, $dompdf->output());

            // Insert into DB or update if exists
            $stmt = $conn->prepare("INSERT INTO payslips (employee_id, month, year, salary, file_path)
                                    VALUES (?, ?, ?, ?, ?)
                                    ON DUPLICATE KEY UPDATE salary=?, file_path=?");
            $stmt->execute([$employee_id, $month, $year, $netPay, $filename, $netPay, $filename]);

            $message = "Payslip generated successfully! <a href='{$filename}' download>Download Now</a>";
        }
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Generate Payslip</title>
<link rel="preconnect" href="https://cdn.jsdelivr.net" crossorigin>
<link rel="dns-prefetch" href="https://cdn.jsdelivr.net">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light p-4">
<div class="container">
    <h2 class="mb-4">Generate Payslip</h2>
    <?php if($message): ?>
        <div class="alert alert-success"><?= $message ?></div>
    <?php endif; ?>
    <form method="POST" class="row g-3">
        <div class="col-md-4">
            <label>Employee</label>
            <select name="employee_id" class="form-select" required>
                <option value="">Select Employee</option>
                <?php foreach($employees as $emp): ?>
                    <option value="<?= $emp['id'] ?>"><?= htmlspecialchars($emp['name']) ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="col-md-2">
            <label>Month</label>
            <select name="month" class="form-select" required>
                <?php for($m=1;$m<=12;$m++):
                    $monthName = date("F", mktime(0,0,0,$m,1)); ?>
                    <option value="<?= $monthName ?>"><?= $monthName ?></option>
                <?php endfor; ?>
            </select>
        </div>
        <div class="col-md-2">
            <label>Year</label>
            <input type="number" name="year" class="form-control" value="<?= date('Y') ?>" required>
        </div>
        <div class="col-md-2">
            <label>Basic Salary</label>
            <input type="number" name="basic" class="form-control" required>
        </div>
        <div class="col-md-2">
            <label>HRA</label>
            <input type="number" name="hra" class="form-control" value="0" required>
        </div>
        <div class="col-md-2">
            <label>Allowance</label>
            <input type="number" name="allowance" class="form-control" value="0" required>
        </div>
        <div class="col-md-2">
            <label>Deductions</label>
            <input type="number" name="deductions" class="form-control" value="0" required>
        </div>
        <div class="col-12 mt-3">
            <button class="btn btn-success">Generate Payslip</button>
            <a href="payslips.php" class="btn btn-secondary">View Payslips</a>
        </div>
    </form>
</div>
</body>
</html>
